/* 
 * DotAAS Part 2 | HTTP/REST | Asset Administration Shell Repository
 *
 * An exemplary interface combination for the use case of an Asset Administration Shell Repository
 *
 * OpenAPI spec version: Final-Draft
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing AccessControlPolicyPoints
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AccessControlPolicyPointsTests
    {
        // TODO uncomment below to declare an instance variable for AccessControlPolicyPoints
        //private AccessControlPolicyPoints instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AccessControlPolicyPoints
            //instance = new AccessControlPolicyPoints();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AccessControlPolicyPoints
        /// </summary>
        [Test]
        public void AccessControlPolicyPointsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AccessControlPolicyPoints
            //Assert.IsInstanceOfType<AccessControlPolicyPoints> (instance, "variable 'instance' is a AccessControlPolicyPoints");
        }


        /// <summary>
        /// Test the property 'PolicyAdministrationPoint'
        /// </summary>
        [Test]
        public void PolicyAdministrationPointTest()
        {
            // TODO unit test for the property 'PolicyAdministrationPoint'
        }
        /// <summary>
        /// Test the property 'PolicyDecisionPoint'
        /// </summary>
        [Test]
        public void PolicyDecisionPointTest()
        {
            // TODO unit test for the property 'PolicyDecisionPoint'
        }
        /// <summary>
        /// Test the property 'PolicyEnforcementPoint'
        /// </summary>
        [Test]
        public void PolicyEnforcementPointTest()
        {
            // TODO unit test for the property 'PolicyEnforcementPoint'
        }
        /// <summary>
        /// Test the property 'PolicyInformationPoints'
        /// </summary>
        [Test]
        public void PolicyInformationPointsTest()
        {
            // TODO unit test for the property 'PolicyInformationPoints'
        }

    }

}
