/* 
 * DotAAS Part 2 | HTTP/REST | Asset Administration Shell Repository
 *
 * An exemplary interface combination for the use case of an Asset Administration Shell Repository
 *
 * OpenAPI spec version: Final-Draft
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing AccessPermissionRule
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AccessPermissionRuleTests
    {
        // TODO uncomment below to declare an instance variable for AccessPermissionRule
        //private AccessPermissionRule instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AccessPermissionRule
            //instance = new AccessPermissionRule();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AccessPermissionRule
        /// </summary>
        [Test]
        public void AccessPermissionRuleInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AccessPermissionRule
            //Assert.IsInstanceOfType<AccessPermissionRule> (instance, "variable 'instance' is a AccessPermissionRule");
        }


        /// <summary>
        /// Test the property 'Qualifiers'
        /// </summary>
        [Test]
        public void QualifiersTest()
        {
            // TODO unit test for the property 'Qualifiers'
        }
        /// <summary>
        /// Test the property 'PermissionsPerObject'
        /// </summary>
        [Test]
        public void PermissionsPerObjectTest()
        {
            // TODO unit test for the property 'PermissionsPerObject'
        }
        /// <summary>
        /// Test the property 'TargetSubjectAttributes'
        /// </summary>
        [Test]
        public void TargetSubjectAttributesTest()
        {
            // TODO unit test for the property 'TargetSubjectAttributes'
        }

    }

}
