/* 
 * DotAAS Part 2 | HTTP/REST | Asset Administration Shell Repository
 *
 * An exemplary interface combination for the use case of an Asset Administration Shell Repository
 *
 * OpenAPI spec version: Final-Draft
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing AccessControl
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AccessControlTests
    {
        // TODO uncomment below to declare an instance variable for AccessControl
        //private AccessControl instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AccessControl
            //instance = new AccessControl();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AccessControl
        /// </summary>
        [Test]
        public void AccessControlInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AccessControl
            //Assert.IsInstanceOfType<AccessControl> (instance, "variable 'instance' is a AccessControl");
        }


        /// <summary>
        /// Test the property 'AccessPermissionRule'
        /// </summary>
        [Test]
        public void AccessPermissionRuleTest()
        {
            // TODO unit test for the property 'AccessPermissionRule'
        }
        /// <summary>
        /// Test the property 'DefaultEnvironmentAttributes'
        /// </summary>
        [Test]
        public void DefaultEnvironmentAttributesTest()
        {
            // TODO unit test for the property 'DefaultEnvironmentAttributes'
        }
        /// <summary>
        /// Test the property 'DefaultPermissions'
        /// </summary>
        [Test]
        public void DefaultPermissionsTest()
        {
            // TODO unit test for the property 'DefaultPermissions'
        }
        /// <summary>
        /// Test the property 'DefaultSubjectAttributes'
        /// </summary>
        [Test]
        public void DefaultSubjectAttributesTest()
        {
            // TODO unit test for the property 'DefaultSubjectAttributes'
        }
        /// <summary>
        /// Test the property 'SelectableEnvironmentAttributes'
        /// </summary>
        [Test]
        public void SelectableEnvironmentAttributesTest()
        {
            // TODO unit test for the property 'SelectableEnvironmentAttributes'
        }
        /// <summary>
        /// Test the property 'SelectablePermissions'
        /// </summary>
        [Test]
        public void SelectablePermissionsTest()
        {
            // TODO unit test for the property 'SelectablePermissions'
        }
        /// <summary>
        /// Test the property 'SelectableSubjectAttributes'
        /// </summary>
        [Test]
        public void SelectableSubjectAttributesTest()
        {
            // TODO unit test for the property 'SelectableSubjectAttributes'
        }

    }

}
