/* 
 * DotAAS Part 2 | HTTP/REST | Asset Administration Shell Repository
 *
 * An exemplary interface combination for the use case of an Asset Administration Shell Repository
 *
 * OpenAPI spec version: Final-Draft
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing AssetAdministrationShell
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AssetAdministrationShellTests
    {
        // TODO uncomment below to declare an instance variable for AssetAdministrationShell
        //private AssetAdministrationShell instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AssetAdministrationShell
            //instance = new AssetAdministrationShell();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AssetAdministrationShell
        /// </summary>
        [Test]
        public void AssetAdministrationShellInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AssetAdministrationShell
            //Assert.IsInstanceOfType<AssetAdministrationShell> (instance, "variable 'instance' is a AssetAdministrationShell");
        }


        /// <summary>
        /// Test the property 'EmbeddedDataSpecifications'
        /// </summary>
        [Test]
        public void EmbeddedDataSpecificationsTest()
        {
            // TODO unit test for the property 'EmbeddedDataSpecifications'
        }
        /// <summary>
        /// Test the property 'AssetInformation'
        /// </summary>
        [Test]
        public void AssetInformationTest()
        {
            // TODO unit test for the property 'AssetInformation'
        }
        /// <summary>
        /// Test the property 'DerivedFrom'
        /// </summary>
        [Test]
        public void DerivedFromTest()
        {
            // TODO unit test for the property 'DerivedFrom'
        }
        /// <summary>
        /// Test the property 'Security'
        /// </summary>
        [Test]
        public void SecurityTest()
        {
            // TODO unit test for the property 'Security'
        }
        /// <summary>
        /// Test the property 'Submodels'
        /// </summary>
        [Test]
        public void SubmodelsTest()
        {
            // TODO unit test for the property 'Submodels'
        }
        /// <summary>
        /// Test the property 'Views'
        /// </summary>
        [Test]
        public void ViewsTest()
        {
            // TODO unit test for the property 'Views'
        }

    }

}
