/* 
 * DotAAS Part 2 | HTTP/REST | Asset Administration Shell Repository
 *
 * An exemplary interface combination for the use case of an Asset Administration Shell Repository
 *
 * OpenAPI spec version: Final-Draft
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing AssetInformation
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AssetInformationTests
    {
        // TODO uncomment below to declare an instance variable for AssetInformation
        //private AssetInformation instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AssetInformation
            //instance = new AssetInformation();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AssetInformation
        /// </summary>
        [Test]
        public void AssetInformationInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AssetInformation
            //Assert.IsInstanceOfType<AssetInformation> (instance, "variable 'instance' is a AssetInformation");
        }


        /// <summary>
        /// Test the property 'AssetKind'
        /// </summary>
        [Test]
        public void AssetKindTest()
        {
            // TODO unit test for the property 'AssetKind'
        }
        /// <summary>
        /// Test the property 'BillOfMaterial'
        /// </summary>
        [Test]
        public void BillOfMaterialTest()
        {
            // TODO unit test for the property 'BillOfMaterial'
        }
        /// <summary>
        /// Test the property 'GlobalAssetId'
        /// </summary>
        [Test]
        public void GlobalAssetIdTest()
        {
            // TODO unit test for the property 'GlobalAssetId'
        }
        /// <summary>
        /// Test the property 'SpecificAssetIds'
        /// </summary>
        [Test]
        public void SpecificAssetIdsTest()
        {
            // TODO unit test for the property 'SpecificAssetIds'
        }
        /// <summary>
        /// Test the property 'Thumbnail'
        /// </summary>
        [Test]
        public void ThumbnailTest()
        {
            // TODO unit test for the property 'Thumbnail'
        }

    }

}
