/* 
 * DotAAS Part 2 | HTTP/REST | Asset Administration Shell Repository
 *
 * An exemplary interface combination for the use case of an Asset Administration Shell Repository
 *
 * OpenAPI spec version: Final-Draft
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing AssetAdministrationShellEnvironment
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AssetAdministrationShellEnvironmentTests
    {
        // TODO uncomment below to declare an instance variable for AssetAdministrationShellEnvironment
        //private AssetAdministrationShellEnvironment instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AssetAdministrationShellEnvironment
            //instance = new AssetAdministrationShellEnvironment();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AssetAdministrationShellEnvironment
        /// </summary>
        [Test]
        public void AssetAdministrationShellEnvironmentInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AssetAdministrationShellEnvironment
            //Assert.IsInstanceOfType<AssetAdministrationShellEnvironment> (instance, "variable 'instance' is a AssetAdministrationShellEnvironment");
        }


        /// <summary>
        /// Test the property 'AssetAdministrationShells'
        /// </summary>
        [Test]
        public void AssetAdministrationShellsTest()
        {
            // TODO unit test for the property 'AssetAdministrationShells'
        }
        /// <summary>
        /// Test the property 'ConceptDescriptions'
        /// </summary>
        [Test]
        public void ConceptDescriptionsTest()
        {
            // TODO unit test for the property 'ConceptDescriptions'
        }
        /// <summary>
        /// Test the property 'Submodels'
        /// </summary>
        [Test]
        public void SubmodelsTest()
        {
            // TODO unit test for the property 'Submodels'
        }

    }

}
