/* 
 * DotAAS Part 2 | HTTP/REST | Asset Administration Shell Repository
 *
 * An exemplary interface combination for the use case of an Asset Administration Shell Repository
 *
 * OpenAPI spec version: Final-Draft
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing BasicEvent
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BasicEventTests
    {
        // TODO uncomment below to declare an instance variable for BasicEvent
        //private BasicEvent instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of BasicEvent
            //instance = new BasicEvent();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BasicEvent
        /// </summary>
        [Test]
        public void BasicEventInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" BasicEvent
            //Assert.IsInstanceOfType<BasicEvent> (instance, "variable 'instance' is a BasicEvent");
        }


        /// <summary>
        /// Test the property 'Observed'
        /// </summary>
        [Test]
        public void ObservedTest()
        {
            // TODO unit test for the property 'Observed'
        }

    }

}
