/* 
 * DotAAS Part 2 | HTTP/REST | Asset Administration Shell Repository
 *
 * An exemplary interface combination for the use case of an Asset Administration Shell Repository
 *
 * OpenAPI spec version: Final-Draft
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing BlobCertificate
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BlobCertificateTests
    {
        // TODO uncomment below to declare an instance variable for BlobCertificate
        //private BlobCertificate instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of BlobCertificate
            //instance = new BlobCertificate();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BlobCertificate
        /// </summary>
        [Test]
        public void BlobCertificateInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" BlobCertificate
            //Assert.IsInstanceOfType<BlobCertificate> (instance, "variable 'instance' is a BlobCertificate");
        }


        /// <summary>
        /// Test the property '_BlobCertificate'
        /// </summary>
        [Test]
        public void _BlobCertificateTest()
        {
            // TODO unit test for the property '_BlobCertificate'
        }
        /// <summary>
        /// Test the property 'ContainedExtension'
        /// </summary>
        [Test]
        public void ContainedExtensionTest()
        {
            // TODO unit test for the property 'ContainedExtension'
        }
        /// <summary>
        /// Test the property 'LastCertificate'
        /// </summary>
        [Test]
        public void LastCertificateTest()
        {
            // TODO unit test for the property 'LastCertificate'
        }

    }

}
