/* 
 * DotAAS Part 2 | HTTP/REST | Asset Administration Shell Repository
 *
 * An exemplary interface combination for the use case of an Asset Administration Shell Repository
 *
 * OpenAPI spec version: Final-Draft
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ConceptDescription
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ConceptDescriptionTests
    {
        // TODO uncomment below to declare an instance variable for ConceptDescription
        //private ConceptDescription instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ConceptDescription
            //instance = new ConceptDescription();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ConceptDescription
        /// </summary>
        [Test]
        public void ConceptDescriptionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ConceptDescription
            //Assert.IsInstanceOfType<ConceptDescription> (instance, "variable 'instance' is a ConceptDescription");
        }


        /// <summary>
        /// Test the property 'EmbeddedDataSpecifications'
        /// </summary>
        [Test]
        public void EmbeddedDataSpecificationsTest()
        {
            // TODO unit test for the property 'EmbeddedDataSpecifications'
        }
        /// <summary>
        /// Test the property 'IsCaseOf'
        /// </summary>
        [Test]
        public void IsCaseOfTest()
        {
            // TODO unit test for the property 'IsCaseOf'
        }

    }

}
