/* 
 * DotAAS Part 2 | HTTP/REST | Asset Administration Shell Repository
 *
 * An exemplary interface combination for the use case of an Asset Administration Shell Repository
 *
 * OpenAPI spec version: Final-Draft
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing DataSpecificationPhysicalUnitContent
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DataSpecificationPhysicalUnitContentTests
    {
        // TODO uncomment below to declare an instance variable for DataSpecificationPhysicalUnitContent
        //private DataSpecificationPhysicalUnitContent instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DataSpecificationPhysicalUnitContent
            //instance = new DataSpecificationPhysicalUnitContent();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DataSpecificationPhysicalUnitContent
        /// </summary>
        [Test]
        public void DataSpecificationPhysicalUnitContentInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DataSpecificationPhysicalUnitContent
            //Assert.IsInstanceOfType<DataSpecificationPhysicalUnitContent> (instance, "variable 'instance' is a DataSpecificationPhysicalUnitContent");
        }


        /// <summary>
        /// Test the property 'ConversionFactor'
        /// </summary>
        [Test]
        public void ConversionFactorTest()
        {
            // TODO unit test for the property 'ConversionFactor'
        }
        /// <summary>
        /// Test the property 'Definition'
        /// </summary>
        [Test]
        public void DefinitionTest()
        {
            // TODO unit test for the property 'Definition'
        }
        /// <summary>
        /// Test the property 'DinNotation'
        /// </summary>
        [Test]
        public void DinNotationTest()
        {
            // TODO unit test for the property 'DinNotation'
        }
        /// <summary>
        /// Test the property 'EceCode'
        /// </summary>
        [Test]
        public void EceCodeTest()
        {
            // TODO unit test for the property 'EceCode'
        }
        /// <summary>
        /// Test the property 'EceName'
        /// </summary>
        [Test]
        public void EceNameTest()
        {
            // TODO unit test for the property 'EceName'
        }
        /// <summary>
        /// Test the property 'NistName'
        /// </summary>
        [Test]
        public void NistNameTest()
        {
            // TODO unit test for the property 'NistName'
        }
        /// <summary>
        /// Test the property 'RegistrationAuthorityId'
        /// </summary>
        [Test]
        public void RegistrationAuthorityIdTest()
        {
            // TODO unit test for the property 'RegistrationAuthorityId'
        }
        /// <summary>
        /// Test the property 'SiName'
        /// </summary>
        [Test]
        public void SiNameTest()
        {
            // TODO unit test for the property 'SiName'
        }
        /// <summary>
        /// Test the property 'SiNotation'
        /// </summary>
        [Test]
        public void SiNotationTest()
        {
            // TODO unit test for the property 'SiNotation'
        }
        /// <summary>
        /// Test the property 'SourceOfDefinition'
        /// </summary>
        [Test]
        public void SourceOfDefinitionTest()
        {
            // TODO unit test for the property 'SourceOfDefinition'
        }
        /// <summary>
        /// Test the property 'Supplier'
        /// </summary>
        [Test]
        public void SupplierTest()
        {
            // TODO unit test for the property 'Supplier'
        }
        /// <summary>
        /// Test the property 'UnitName'
        /// </summary>
        [Test]
        public void UnitNameTest()
        {
            // TODO unit test for the property 'UnitName'
        }
        /// <summary>
        /// Test the property 'UnitSymbol'
        /// </summary>
        [Test]
        public void UnitSymbolTest()
        {
            // TODO unit test for the property 'UnitSymbol'
        }

    }

}
