/* 
 * DotAAS Part 2 | HTTP/REST | Asset Administration Shell Repository
 *
 * An exemplary interface combination for the use case of an Asset Administration Shell Repository
 *
 * OpenAPI spec version: Final-Draft
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing DataSpecificationIEC61360Content
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DataSpecificationIEC61360ContentTests
    {
        // TODO uncomment below to declare an instance variable for DataSpecificationIEC61360Content
        //private DataSpecificationIEC61360Content instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DataSpecificationIEC61360Content
            //instance = new DataSpecificationIEC61360Content();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DataSpecificationIEC61360Content
        /// </summary>
        [Test]
        public void DataSpecificationIEC61360ContentInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DataSpecificationIEC61360Content
            //Assert.IsInstanceOfType<DataSpecificationIEC61360Content> (instance, "variable 'instance' is a DataSpecificationIEC61360Content");
        }


        /// <summary>
        /// Test the property 'DataType'
        /// </summary>
        [Test]
        public void DataTypeTest()
        {
            // TODO unit test for the property 'DataType'
        }
        /// <summary>
        /// Test the property 'Definition'
        /// </summary>
        [Test]
        public void DefinitionTest()
        {
            // TODO unit test for the property 'Definition'
        }
        /// <summary>
        /// Test the property 'LevelType'
        /// </summary>
        [Test]
        public void LevelTypeTest()
        {
            // TODO unit test for the property 'LevelType'
        }
        /// <summary>
        /// Test the property 'PreferredName'
        /// </summary>
        [Test]
        public void PreferredNameTest()
        {
            // TODO unit test for the property 'PreferredName'
        }
        /// <summary>
        /// Test the property 'ShortName'
        /// </summary>
        [Test]
        public void ShortNameTest()
        {
            // TODO unit test for the property 'ShortName'
        }
        /// <summary>
        /// Test the property 'SourceOfDefinition'
        /// </summary>
        [Test]
        public void SourceOfDefinitionTest()
        {
            // TODO unit test for the property 'SourceOfDefinition'
        }
        /// <summary>
        /// Test the property 'Symbol'
        /// </summary>
        [Test]
        public void SymbolTest()
        {
            // TODO unit test for the property 'Symbol'
        }
        /// <summary>
        /// Test the property 'Unit'
        /// </summary>
        [Test]
        public void UnitTest()
        {
            // TODO unit test for the property 'Unit'
        }
        /// <summary>
        /// Test the property 'UnitId'
        /// </summary>
        [Test]
        public void UnitIdTest()
        {
            // TODO unit test for the property 'UnitId'
        }
        /// <summary>
        /// Test the property 'ValueFormat'
        /// </summary>
        [Test]
        public void ValueFormatTest()
        {
            // TODO unit test for the property 'ValueFormat'
        }
        /// <summary>
        /// Test the property 'ValueList'
        /// </summary>
        [Test]
        public void ValueListTest()
        {
            // TODO unit test for the property 'ValueList'
        }

    }

}
