/* 
 * DotAAS Part 2 | HTTP/REST | Asset Administration Shell Repository
 *
 * An exemplary interface combination for the use case of an Asset Administration Shell Repository
 *
 * OpenAPI spec version: Final-Draft
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing EmbeddedDataSpecification
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class EmbeddedDataSpecificationTests
    {
        // TODO uncomment below to declare an instance variable for EmbeddedDataSpecification
        //private EmbeddedDataSpecification instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of EmbeddedDataSpecification
            //instance = new EmbeddedDataSpecification();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of EmbeddedDataSpecification
        /// </summary>
        [Test]
        public void EmbeddedDataSpecificationInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" EmbeddedDataSpecification
            //Assert.IsInstanceOfType<EmbeddedDataSpecification> (instance, "variable 'instance' is a EmbeddedDataSpecification");
        }


        /// <summary>
        /// Test the property 'DataSpecification'
        /// </summary>
        [Test]
        public void DataSpecificationTest()
        {
            // TODO unit test for the property 'DataSpecification'
        }
        /// <summary>
        /// Test the property 'DataSpecificationContent'
        /// </summary>
        [Test]
        public void DataSpecificationContentTest()
        {
            // TODO unit test for the property 'DataSpecificationContent'
        }

    }

}
