/* 
 * DotAAS Part 2 | HTTP/REST | Asset Administration Shell Repository
 *
 * An exemplary interface combination for the use case of an Asset Administration Shell Repository
 *
 * OpenAPI spec version: Final-Draft
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Entity
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class EntityTests
    {
        // TODO uncomment below to declare an instance variable for Entity
        //private Entity instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Entity
            //instance = new Entity();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Entity
        /// </summary>
        [Test]
        public void EntityInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Entity
            //Assert.IsInstanceOfType<Entity> (instance, "variable 'instance' is a Entity");
        }


        /// <summary>
        /// Test the property 'EntityType'
        /// </summary>
        [Test]
        public void EntityTypeTest()
        {
            // TODO unit test for the property 'EntityType'
        }
        /// <summary>
        /// Test the property 'GlobalAssetId'
        /// </summary>
        [Test]
        public void GlobalAssetIdTest()
        {
            // TODO unit test for the property 'GlobalAssetId'
        }
        /// <summary>
        /// Test the property 'SpecificAssetIds'
        /// </summary>
        [Test]
        public void SpecificAssetIdsTest()
        {
            // TODO unit test for the property 'SpecificAssetIds'
        }
        /// <summary>
        /// Test the property 'Statements'
        /// </summary>
        [Test]
        public void StatementsTest()
        {
            // TODO unit test for the property 'Statements'
        }

    }

}
