/* 
 * DotAAS Part 2 | HTTP/REST | Asset Administration Shell Repository
 *
 * An exemplary interface combination for the use case of an Asset Administration Shell Repository
 *
 * OpenAPI spec version: Final-Draft
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ModelReference
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ModelReferenceTests
    {
        // TODO uncomment below to declare an instance variable for ModelReference
        //private ModelReference instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ModelReference
            //instance = new ModelReference();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ModelReference
        /// </summary>
        [Test]
        public void ModelReferenceInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ModelReference
            //Assert.IsInstanceOfType<ModelReference> (instance, "variable 'instance' is a ModelReference");
        }


        /// <summary>
        /// Test the property 'ReferredSemanticId'
        /// </summary>
        [Test]
        public void ReferredSemanticIdTest()
        {
            // TODO unit test for the property 'ReferredSemanticId'
        }
        /// <summary>
        /// Test the property 'Keys'
        /// </summary>
        [Test]
        public void KeysTest()
        {
            // TODO unit test for the property 'Keys'
        }

    }

}
