/* 
 * DotAAS Part 2 | HTTP/REST | Asset Administration Shell Repository
 *
 * An exemplary interface combination for the use case of an Asset Administration Shell Repository
 *
 * OpenAPI spec version: Final-Draft
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing MultiLanguageProperty
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class MultiLanguagePropertyTests
    {
        // TODO uncomment below to declare an instance variable for MultiLanguageProperty
        //private MultiLanguageProperty instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of MultiLanguageProperty
            //instance = new MultiLanguageProperty();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of MultiLanguageProperty
        /// </summary>
        [Test]
        public void MultiLanguagePropertyInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" MultiLanguageProperty
            //Assert.IsInstanceOfType<MultiLanguageProperty> (instance, "variable 'instance' is a MultiLanguageProperty");
        }


        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Test]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }
        /// <summary>
        /// Test the property 'ValueId'
        /// </summary>
        [Test]
        public void ValueIdTest()
        {
            // TODO unit test for the property 'ValueId'
        }

    }

}
