/* 
 * DotAAS Part 2 | HTTP/REST | Asset Administration Shell Repository
 *
 * An exemplary interface combination for the use case of an Asset Administration Shell Repository
 *
 * OpenAPI spec version: Final-Draft
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ObjectAttributes
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ObjectAttributesTests
    {
        // TODO uncomment below to declare an instance variable for ObjectAttributes
        //private ObjectAttributes instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ObjectAttributes
            //instance = new ObjectAttributes();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ObjectAttributes
        /// </summary>
        [Test]
        public void ObjectAttributesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ObjectAttributes
            //Assert.IsInstanceOfType<ObjectAttributes> (instance, "variable 'instance' is a ObjectAttributes");
        }


        /// <summary>
        /// Test the property 'ObjectAttribute'
        /// </summary>
        [Test]
        public void ObjectAttributeTest()
        {
            // TODO unit test for the property 'ObjectAttribute'
        }

    }

}
