/* 
 * DotAAS Part 2 | HTTP/REST | Asset Administration Shell Repository
 *
 * An exemplary interface combination for the use case of an Asset Administration Shell Repository
 *
 * OpenAPI spec version: Final-Draft
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Operation
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class OperationTests
    {
        // TODO uncomment below to declare an instance variable for Operation
        //private Operation instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Operation
            //instance = new Operation();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Operation
        /// </summary>
        [Test]
        public void OperationInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Operation
            //Assert.IsInstanceOfType<Operation> (instance, "variable 'instance' is a Operation");
        }


        /// <summary>
        /// Test the property 'InoutputVariable'
        /// </summary>
        [Test]
        public void InoutputVariableTest()
        {
            // TODO unit test for the property 'InoutputVariable'
        }
        /// <summary>
        /// Test the property 'InputVariable'
        /// </summary>
        [Test]
        public void InputVariableTest()
        {
            // TODO unit test for the property 'InputVariable'
        }
        /// <summary>
        /// Test the property 'OutputVariable'
        /// </summary>
        [Test]
        public void OutputVariableTest()
        {
            // TODO unit test for the property 'OutputVariable'
        }

    }

}
