/* 
 * DotAAS Part 2 | HTTP/REST | Asset Administration Shell Repository
 *
 * An exemplary interface combination for the use case of an Asset Administration Shell Repository
 *
 * OpenAPI spec version: Final-Draft
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing OperationResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class OperationResultTests
    {
        // TODO uncomment below to declare an instance variable for OperationResult
        //private OperationResult instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of OperationResult
            //instance = new OperationResult();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of OperationResult
        /// </summary>
        [Test]
        public void OperationResultInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" OperationResult
            //Assert.IsInstanceOfType<OperationResult> (instance, "variable 'instance' is a OperationResult");
        }


        /// <summary>
        /// Test the property 'ExecutionResult'
        /// </summary>
        [Test]
        public void ExecutionResultTest()
        {
            // TODO unit test for the property 'ExecutionResult'
        }
        /// <summary>
        /// Test the property 'ExecutionState'
        /// </summary>
        [Test]
        public void ExecutionStateTest()
        {
            // TODO unit test for the property 'ExecutionState'
        }
        /// <summary>
        /// Test the property 'InoutputArguments'
        /// </summary>
        [Test]
        public void InoutputArgumentsTest()
        {
            // TODO unit test for the property 'InoutputArguments'
        }
        /// <summary>
        /// Test the property 'OutputArguments'
        /// </summary>
        [Test]
        public void OutputArgumentsTest()
        {
            // TODO unit test for the property 'OutputArguments'
        }
        /// <summary>
        /// Test the property 'RequestId'
        /// </summary>
        [Test]
        public void RequestIdTest()
        {
            // TODO unit test for the property 'RequestId'
        }

    }

}
