/* 
 * DotAAS Part 2 | HTTP/REST | Asset Administration Shell Repository
 *
 * An exemplary interface combination for the use case of an Asset Administration Shell Repository
 *
 * OpenAPI spec version: Final-Draft
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing OperationRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class OperationRequestTests
    {
        // TODO uncomment below to declare an instance variable for OperationRequest
        //private OperationRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of OperationRequest
            //instance = new OperationRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of OperationRequest
        /// </summary>
        [Test]
        public void OperationRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" OperationRequest
            //Assert.IsInstanceOfType<OperationRequest> (instance, "variable 'instance' is a OperationRequest");
        }


        /// <summary>
        /// Test the property 'InoutputArguments'
        /// </summary>
        [Test]
        public void InoutputArgumentsTest()
        {
            // TODO unit test for the property 'InoutputArguments'
        }
        /// <summary>
        /// Test the property 'InputArguments'
        /// </summary>
        [Test]
        public void InputArgumentsTest()
        {
            // TODO unit test for the property 'InputArguments'
        }
        /// <summary>
        /// Test the property 'RequestId'
        /// </summary>
        [Test]
        public void RequestIdTest()
        {
            // TODO unit test for the property 'RequestId'
        }
        /// <summary>
        /// Test the property 'Timeout'
        /// </summary>
        [Test]
        public void TimeoutTest()
        {
            // TODO unit test for the property 'Timeout'
        }

    }

}
