/* 
 * DotAAS Part 2 | HTTP/REST | Asset Administration Shell Repository
 *
 * An exemplary interface combination for the use case of an Asset Administration Shell Repository
 *
 * OpenAPI spec version: Final-Draft
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing PermissionsPerObject
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PermissionsPerObjectTests
    {
        // TODO uncomment below to declare an instance variable for PermissionsPerObject
        //private PermissionsPerObject instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PermissionsPerObject
            //instance = new PermissionsPerObject();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PermissionsPerObject
        /// </summary>
        [Test]
        public void PermissionsPerObjectInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PermissionsPerObject
            //Assert.IsInstanceOfType<PermissionsPerObject> (instance, "variable 'instance' is a PermissionsPerObject");
        }


        /// <summary>
        /// Test the property '_Object'
        /// </summary>
        [Test]
        public void _ObjectTest()
        {
            // TODO unit test for the property '_Object'
        }
        /// <summary>
        /// Test the property 'Permission'
        /// </summary>
        [Test]
        public void PermissionTest()
        {
            // TODO unit test for the property 'Permission'
        }
        /// <summary>
        /// Test the property 'TargetObjectAttributes'
        /// </summary>
        [Test]
        public void TargetObjectAttributesTest()
        {
            // TODO unit test for the property 'TargetObjectAttributes'
        }

    }

}
