/* 
 * DotAAS Part 2 | HTTP/REST | Asset Administration Shell Repository
 *
 * An exemplary interface combination for the use case of an Asset Administration Shell Repository
 *
 * OpenAPI spec version: Final-Draft
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Permission
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PermissionTests
    {
        // TODO uncomment below to declare an instance variable for Permission
        //private Permission instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Permission
            //instance = new Permission();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Permission
        /// </summary>
        [Test]
        public void PermissionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Permission
            //Assert.IsInstanceOfType<Permission> (instance, "variable 'instance' is a Permission");
        }


        /// <summary>
        /// Test the property 'KindOfPermission'
        /// </summary>
        [Test]
        public void KindOfPermissionTest()
        {
            // TODO unit test for the property 'KindOfPermission'
        }
        /// <summary>
        /// Test the property '_Permission'
        /// </summary>
        [Test]
        public void _PermissionTest()
        {
            // TODO unit test for the property '_Permission'
        }

    }

}
