/* 
 * DotAAS Part 2 | HTTP/REST | Asset Administration Shell Repository
 *
 * An exemplary interface combination for the use case of an Asset Administration Shell Repository
 *
 * OpenAPI spec version: Final-Draft
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing PolicyAdministrationPoint
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PolicyAdministrationPointTests
    {
        // TODO uncomment below to declare an instance variable for PolicyAdministrationPoint
        //private PolicyAdministrationPoint instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PolicyAdministrationPoint
            //instance = new PolicyAdministrationPoint();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PolicyAdministrationPoint
        /// </summary>
        [Test]
        public void PolicyAdministrationPointInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PolicyAdministrationPoint
            //Assert.IsInstanceOfType<PolicyAdministrationPoint> (instance, "variable 'instance' is a PolicyAdministrationPoint");
        }


        /// <summary>
        /// Test the property 'ExternalAccessControl'
        /// </summary>
        [Test]
        public void ExternalAccessControlTest()
        {
            // TODO unit test for the property 'ExternalAccessControl'
        }
        /// <summary>
        /// Test the property 'LocalAccessControl'
        /// </summary>
        [Test]
        public void LocalAccessControlTest()
        {
            // TODO unit test for the property 'LocalAccessControl'
        }

    }

}
