/* 
 * DotAAS Part 2 | HTTP/REST | Asset Administration Shell Repository
 *
 * An exemplary interface combination for the use case of an Asset Administration Shell Repository
 *
 * OpenAPI spec version: Final-Draft
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Security
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SecurityTests
    {
        // TODO uncomment below to declare an instance variable for Security
        //private Security instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Security
            //instance = new Security();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Security
        /// </summary>
        [Test]
        public void SecurityInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Security
            //Assert.IsInstanceOfType<Security> (instance, "variable 'instance' is a Security");
        }


        /// <summary>
        /// Test the property 'AccessControlPolicyPoints'
        /// </summary>
        [Test]
        public void AccessControlPolicyPointsTest()
        {
            // TODO unit test for the property 'AccessControlPolicyPoints'
        }
        /// <summary>
        /// Test the property 'Certificate'
        /// </summary>
        [Test]
        public void CertificateTest()
        {
            // TODO unit test for the property 'Certificate'
        }
        /// <summary>
        /// Test the property 'RequiredCertificateExtension'
        /// </summary>
        [Test]
        public void RequiredCertificateExtensionTest()
        {
            // TODO unit test for the property 'RequiredCertificateExtension'
        }

    }

}
