/* 
 * DotAAS Part 2 | HTTP/REST | Asset Administration Shell Repository
 *
 * An exemplary interface combination for the use case of an Asset Administration Shell Repository
 *
 * OpenAPI spec version: Final-Draft
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing SubjectAttributes
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SubjectAttributesTests
    {
        // TODO uncomment below to declare an instance variable for SubjectAttributes
        //private SubjectAttributes instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SubjectAttributes
            //instance = new SubjectAttributes();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SubjectAttributes
        /// </summary>
        [Test]
        public void SubjectAttributesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SubjectAttributes
            //Assert.IsInstanceOfType<SubjectAttributes> (instance, "variable 'instance' is a SubjectAttributes");
        }


        /// <summary>
        /// Test the property '_SubjectAttributes'
        /// </summary>
        [Test]
        public void _SubjectAttributesTest()
        {
            // TODO unit test for the property '_SubjectAttributes'
        }

    }

}
