/* 
 * DotAAS Part 2 | HTTP/REST | Asset Administration Shell Repository
 *
 * An exemplary interface combination for the use case of an Asset Administration Shell Repository
 *
 * OpenAPI spec version: Final-Draft
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Submodel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SubmodelTests
    {
        // TODO uncomment below to declare an instance variable for Submodel
        //private Submodel instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Submodel
            //instance = new Submodel();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Submodel
        /// </summary>
        [Test]
        public void SubmodelInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Submodel
            //Assert.IsInstanceOfType<Submodel> (instance, "variable 'instance' is a Submodel");
        }


        /// <summary>
        /// Test the property 'EmbeddedDataSpecifications'
        /// </summary>
        [Test]
        public void EmbeddedDataSpecificationsTest()
        {
            // TODO unit test for the property 'EmbeddedDataSpecifications'
        }
        /// <summary>
        /// Test the property 'Qualifiers'
        /// </summary>
        [Test]
        public void QualifiersTest()
        {
            // TODO unit test for the property 'Qualifiers'
        }
        /// <summary>
        /// Test the property 'SemanticId'
        /// </summary>
        [Test]
        public void SemanticIdTest()
        {
            // TODO unit test for the property 'SemanticId'
        }
        /// <summary>
        /// Test the property 'Kind'
        /// </summary>
        [Test]
        public void KindTest()
        {
            // TODO unit test for the property 'Kind'
        }
        /// <summary>
        /// Test the property 'SubmodelElements'
        /// </summary>
        [Test]
        public void SubmodelElementsTest()
        {
            // TODO unit test for the property 'SubmodelElements'
        }

    }

}
