/* 
 * DotAAS Part 2 | HTTP/REST | Asset Administration Shell Repository
 *
 * An exemplary interface combination for the use case of an Asset Administration Shell Repository
 *
 * OpenAPI spec version: Final-Draft
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing SubmodelElementList
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SubmodelElementListTests
    {
        // TODO uncomment below to declare an instance variable for SubmodelElementList
        //private SubmodelElementList instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SubmodelElementList
            //instance = new SubmodelElementList();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SubmodelElementList
        /// </summary>
        [Test]
        public void SubmodelElementListInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SubmodelElementList
            //Assert.IsInstanceOfType<SubmodelElementList> (instance, "variable 'instance' is a SubmodelElementList");
        }


        /// <summary>
        /// Test the property 'SemanticIdValues'
        /// </summary>
        [Test]
        public void SemanticIdValuesTest()
        {
            // TODO unit test for the property 'SemanticIdValues'
        }
        /// <summary>
        /// Test the property 'SubmodelElementTypeValues'
        /// </summary>
        [Test]
        public void SubmodelElementTypeValuesTest()
        {
            // TODO unit test for the property 'SubmodelElementTypeValues'
        }
        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Test]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }
        /// <summary>
        /// Test the property 'ValueTypeValues'
        /// </summary>
        [Test]
        public void ValueTypeValuesTest()
        {
            // TODO unit test for the property 'ValueTypeValues'
        }

    }

}
