/* 
 * DotAAS Part 2 | HTTP/REST | Asset Administration Shell Repository
 *
 * An exemplary interface combination for the use case of an Asset Administration Shell Repository
 *
 * OpenAPI spec version: Final-Draft
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ValueList
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ValueListTests
    {
        // TODO uncomment below to declare an instance variable for ValueList
        //private ValueList instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ValueList
            //instance = new ValueList();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ValueList
        /// </summary>
        [Test]
        public void ValueListInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ValueList
            //Assert.IsInstanceOfType<ValueList> (instance, "variable 'instance' is a ValueList");
        }


        /// <summary>
        /// Test the property 'ValueReferencePairTypes'
        /// </summary>
        [Test]
        public void ValueReferencePairTypesTest()
        {
            // TODO unit test for the property 'ValueReferencePairTypes'
        }

    }

}
